#数据库连接配置信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shijie?useUnicode=true&characterEncoding=utf8
    data-username: shijie
    password: shijie
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      initial-size: 5 #初始化提供的连接数
      max-idle: 10  #最大的连接数
      max-wait-millis: 2000  #等待连接获取的最大超时时间
server:
  port: 8888 #端口
  servlet:
    context-path: /shijie  #上下文
